# https://taskfile.dev

version: '2'

tasks:
  default:
    cmds:
      - python scripts/venv_check.py
    silent: true

  build:
    dir: StepFunctionsProofOfConcept/src/StepFunctionsProofOfConcept/
    cmds:
      - dotnet clean --output ../../../build
      - dotnet publish --output ../../../build
      - dotnet lambda package -o ../../../release/latest.zip

  install:
    depts: [default]
    cmds: 
      - dotnet restore
      - pip3 install -r requirements.txt 
      - yarn install
        
  test: 
    depts: [default, install] 
    cmds:
      - dotnet test